// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api.proto
// Protobuf C++ Version: 5.29.3

#include "api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace api {
              template <typename>
PROTOBUF_CONSTEXPR RespPush::RespPush(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct RespPushDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespPushDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespPushDefaultTypeInternal() {}
  union {
    RespPush _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespPushDefaultTypeInternal _RespPush_default_instance_;

inline constexpr RespLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : accesstoken_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RespLogin::RespLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RespLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespLoginDefaultTypeInternal() {}
  union {
    RespLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespLoginDefaultTypeInternal _RespLogin_default_instance_;

inline constexpr RespHello::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : challenge_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        revision_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RespHello::RespHello(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RespHelloDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespHelloDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespHelloDefaultTypeInternal() {}
  union {
    RespHello _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespHelloDefaultTypeInternal _RespHello_default_instance_;

inline constexpr ReqLogin::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        serverside_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReqLogin::ReqLogin(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReqLoginDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqLoginDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqLoginDefaultTypeInternal() {}
  union {
    ReqLogin _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqLoginDefaultTypeInternal _ReqLogin_default_instance_;

inline constexpr ReqHello::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : version_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReqHello::ReqHello(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ReqHelloDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqHelloDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqHelloDefaultTypeInternal() {}
  union {
    ReqHello _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqHelloDefaultTypeInternal _ReqHello_default_instance_;
}  // namespace api
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_api_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_api_2eproto = nullptr;
const ::uint32_t
    TableStruct_api_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::ReqHello, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::ReqHello, _impl_.version_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::RespHello, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::RespHello, _impl_.revision_),
        PROTOBUF_FIELD_OFFSET(::api::RespHello, _impl_.challenge_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::ReqLogin, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::ReqLogin, _impl_.clientid_),
        PROTOBUF_FIELD_OFFSET(::api::ReqLogin, _impl_.hash_),
        PROTOBUF_FIELD_OFFSET(::api::ReqLogin, _impl_.serverside_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::RespLogin, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::RespLogin, _impl_.accesstoken_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::RespPush, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::api::ReqHello)},
        {9, -1, -1, sizeof(::api::RespHello)},
        {19, -1, -1, sizeof(::api::ReqLogin)},
        {30, -1, -1, sizeof(::api::RespLogin)},
        {39, -1, -1, sizeof(::api::RespPush)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::api::_ReqHello_default_instance_._instance,
    &::api::_RespHello_default_instance_._instance,
    &::api::_ReqLogin_default_instance_._instance,
    &::api::_RespLogin_default_instance_._instance,
    &::api::_RespPush_default_instance_._instance,
};
const char descriptor_table_protodef_api_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tapi.proto\022\003api\032\017analytics.proto\"\033\n\010Req"
    "Hello\022\017\n\007version\030\001 \001(\005\"0\n\tRespHello\022\020\n\010r"
    "evision\030\001 \001(\005\022\021\n\tchallenge\030\002 \001(\014\">\n\010ReqL"
    "ogin\022\020\n\010clientId\030\001 \001(\014\022\014\n\004hash\030\002 \001(\014\022\022\n\n"
    "serverSide\030\003 \001(\010\" \n\tRespLogin\022\023\n\013accessT"
    "oken\030\002 \001(\t\"\n\n\010RespPush2\226\001\n\017AnalyticsServ"
    "er\022&\n\005Hello\022\r.api.ReqHello\032\016.api.RespHel"
    "lo\022&\n\005Login\022\r.api.ReqLogin\032\016.api.RespLog"
    "in\0223\n\013PushMetrics\022\025.api.AnalyticsMetrics"
    "\032\r.api.RespPushB!Z\037kudzutechnologies/ana"
    "lytics/apib\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_api_2eproto_deps[1] =
    {
        &::descriptor_table_analytics_2eproto,
};
static ::absl::once_flag descriptor_table_api_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_2eproto = {
    false,
    false,
    418,
    descriptor_table_protodef_api_2eproto,
    "api.proto",
    &descriptor_table_api_2eproto_once,
    descriptor_table_api_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_api_2eproto::offsets,
    file_level_enum_descriptors_api_2eproto,
    file_level_service_descriptors_api_2eproto,
};
namespace api {
// ===================================================================

class ReqHello::_Internal {
 public:
};

ReqHello::ReqHello(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.ReqHello)
}
ReqHello::ReqHello(
    ::google::protobuf::Arena* arena, const ReqHello& from)
    : ReqHello(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ReqHello::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ReqHello::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.version_ = {};
}
ReqHello::~ReqHello() {
  // @@protoc_insertion_point(destructor:api.ReqHello)
  SharedDtor(*this);
}
inline void ReqHello::SharedDtor(MessageLite& self) {
  ReqHello& this_ = static_cast<ReqHello&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ReqHello::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReqHello(arena);
}
constexpr auto ReqHello::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ReqHello),
                                            alignof(ReqHello));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReqHello::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReqHello_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReqHello::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReqHello>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReqHello::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReqHello>(), &ReqHello::ByteSizeLong,
            &ReqHello::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReqHello, _impl_._cached_size_),
        false,
    },
    &ReqHello::kDescriptorMethods,
    &descriptor_table_api_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReqHello::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ReqHello::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::ReqHello>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ReqHello, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ReqHello, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 version = 1;
    {PROTOBUF_FIELD_OFFSET(ReqHello, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ReqHello::Clear() {
// @@protoc_insertion_point(message_clear_start:api.ReqHello)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReqHello::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReqHello& this_ = static_cast<const ReqHello&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReqHello::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReqHello& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.ReqHello)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 version = 1;
          if (this_._internal_version() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_version(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.ReqHello)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReqHello::ByteSizeLong(const MessageLite& base) {
          const ReqHello& this_ = static_cast<const ReqHello&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReqHello::ByteSizeLong() const {
          const ReqHello& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.ReqHello)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 version = 1;
            if (this_._internal_version() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_version());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReqHello::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReqHello*>(&to_msg);
  auto& from = static_cast<const ReqHello&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.ReqHello)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_version() != 0) {
    _this->_impl_.version_ = from._impl_.version_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReqHello::CopyFrom(const ReqHello& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.ReqHello)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReqHello::InternalSwap(ReqHello* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata ReqHello::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RespHello::_Internal {
 public:
};

RespHello::RespHello(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.RespHello)
}
inline PROTOBUF_NDEBUG_INLINE RespHello::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::RespHello& from_msg)
      : challenge_(arena, from.challenge_),
        _cached_size_{0} {}

RespHello::RespHello(
    ::google::protobuf::Arena* arena,
    const RespHello& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RespHello* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.revision_ = from._impl_.revision_;

  // @@protoc_insertion_point(copy_constructor:api.RespHello)
}
inline PROTOBUF_NDEBUG_INLINE RespHello::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : challenge_(arena),
        _cached_size_{0} {}

inline void RespHello::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.revision_ = {};
}
RespHello::~RespHello() {
  // @@protoc_insertion_point(destructor:api.RespHello)
  SharedDtor(*this);
}
inline void RespHello::SharedDtor(MessageLite& self) {
  RespHello& this_ = static_cast<RespHello&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.challenge_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RespHello::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RespHello(arena);
}
constexpr auto RespHello::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RespHello),
                                            alignof(RespHello));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RespHello::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RespHello_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RespHello::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RespHello>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RespHello::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RespHello>(), &RespHello::ByteSizeLong,
            &RespHello::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RespHello, _impl_._cached_size_),
        false,
    },
    &RespHello::kDescriptorMethods,
    &descriptor_table_api_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RespHello::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> RespHello::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::RespHello>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes challenge = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RespHello, _impl_.challenge_)}},
    // int32 revision = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RespHello, _impl_.revision_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RespHello, _impl_.revision_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 revision = 1;
    {PROTOBUF_FIELD_OFFSET(RespHello, _impl_.revision_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bytes challenge = 2;
    {PROTOBUF_FIELD_OFFSET(RespHello, _impl_.challenge_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void RespHello::Clear() {
// @@protoc_insertion_point(message_clear_start:api.RespHello)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.challenge_.ClearToEmpty();
  _impl_.revision_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RespHello::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RespHello& this_ = static_cast<const RespHello&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RespHello::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RespHello& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.RespHello)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 revision = 1;
          if (this_._internal_revision() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_revision(), target);
          }

          // bytes challenge = 2;
          if (!this_._internal_challenge().empty()) {
            const std::string& _s = this_._internal_challenge();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.RespHello)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RespHello::ByteSizeLong(const MessageLite& base) {
          const RespHello& this_ = static_cast<const RespHello&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RespHello::ByteSizeLong() const {
          const RespHello& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.RespHello)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes challenge = 2;
            if (!this_._internal_challenge().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_challenge());
            }
            // int32 revision = 1;
            if (this_._internal_revision() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_revision());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RespHello::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RespHello*>(&to_msg);
  auto& from = static_cast<const RespHello&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.RespHello)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_challenge().empty()) {
    _this->_internal_set_challenge(from._internal_challenge());
  }
  if (from._internal_revision() != 0) {
    _this->_impl_.revision_ = from._impl_.revision_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RespHello::CopyFrom(const RespHello& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.RespHello)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RespHello::InternalSwap(RespHello* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.challenge_, &other->_impl_.challenge_, arena);
        swap(_impl_.revision_, other->_impl_.revision_);
}

::google::protobuf::Metadata RespHello::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ReqLogin::_Internal {
 public:
};

ReqLogin::ReqLogin(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.ReqLogin)
}
inline PROTOBUF_NDEBUG_INLINE ReqLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::ReqLogin& from_msg)
      : clientid_(arena, from.clientid_),
        hash_(arena, from.hash_),
        _cached_size_{0} {}

ReqLogin::ReqLogin(
    ::google::protobuf::Arena* arena,
    const ReqLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ReqLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.serverside_ = from._impl_.serverside_;

  // @@protoc_insertion_point(copy_constructor:api.ReqLogin)
}
inline PROTOBUF_NDEBUG_INLINE ReqLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : clientid_(arena),
        hash_(arena),
        _cached_size_{0} {}

inline void ReqLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.serverside_ = {};
}
ReqLogin::~ReqLogin() {
  // @@protoc_insertion_point(destructor:api.ReqLogin)
  SharedDtor(*this);
}
inline void ReqLogin::SharedDtor(MessageLite& self) {
  ReqLogin& this_ = static_cast<ReqLogin&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.clientid_.Destroy();
  this_._impl_.hash_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ReqLogin::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ReqLogin(arena);
}
constexpr auto ReqLogin::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ReqLogin),
                                            alignof(ReqLogin));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ReqLogin::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ReqLogin_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ReqLogin::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ReqLogin>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ReqLogin::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ReqLogin>(), &ReqLogin::ByteSizeLong,
            &ReqLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_._cached_size_),
        false,
    },
    &ReqLogin::kDescriptorMethods,
    &descriptor_table_api_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ReqLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ReqLogin::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::ReqLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes clientId = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.clientid_)}},
    // bytes hash = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.hash_)}},
    // bool serverSide = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ReqLogin, _impl_.serverside_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.serverside_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes clientId = 1;
    {PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.clientid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes hash = 2;
    {PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.hash_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bool serverSide = 3;
    {PROTOBUF_FIELD_OFFSET(ReqLogin, _impl_.serverside_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ReqLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:api.ReqLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clientid_.ClearToEmpty();
  _impl_.hash_.ClearToEmpty();
  _impl_.serverside_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ReqLogin::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ReqLogin& this_ = static_cast<const ReqLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ReqLogin::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ReqLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.ReqLogin)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes clientId = 1;
          if (!this_._internal_clientid().empty()) {
            const std::string& _s = this_._internal_clientid();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // bytes hash = 2;
          if (!this_._internal_hash().empty()) {
            const std::string& _s = this_._internal_hash();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // bool serverSide = 3;
          if (this_._internal_serverside() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_serverside(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.ReqLogin)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ReqLogin::ByteSizeLong(const MessageLite& base) {
          const ReqLogin& this_ = static_cast<const ReqLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ReqLogin::ByteSizeLong() const {
          const ReqLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.ReqLogin)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes clientId = 1;
            if (!this_._internal_clientid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_clientid());
            }
            // bytes hash = 2;
            if (!this_._internal_hash().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_hash());
            }
            // bool serverSide = 3;
            if (this_._internal_serverside() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ReqLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ReqLogin*>(&to_msg);
  auto& from = static_cast<const ReqLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.ReqLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_clientid().empty()) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  if (!from._internal_hash().empty()) {
    _this->_internal_set_hash(from._internal_hash());
  }
  if (from._internal_serverside() != 0) {
    _this->_impl_.serverside_ = from._impl_.serverside_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReqLogin::CopyFrom(const ReqLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.ReqLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ReqLogin::InternalSwap(ReqLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hash_, &other->_impl_.hash_, arena);
        swap(_impl_.serverside_, other->_impl_.serverside_);
}

::google::protobuf::Metadata ReqLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RespLogin::_Internal {
 public:
};

RespLogin::RespLogin(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.RespLogin)
}
inline PROTOBUF_NDEBUG_INLINE RespLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::RespLogin& from_msg)
      : accesstoken_(arena, from.accesstoken_),
        _cached_size_{0} {}

RespLogin::RespLogin(
    ::google::protobuf::Arena* arena,
    const RespLogin& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RespLogin* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:api.RespLogin)
}
inline PROTOBUF_NDEBUG_INLINE RespLogin::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : accesstoken_(arena),
        _cached_size_{0} {}

inline void RespLogin::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RespLogin::~RespLogin() {
  // @@protoc_insertion_point(destructor:api.RespLogin)
  SharedDtor(*this);
}
inline void RespLogin::SharedDtor(MessageLite& self) {
  RespLogin& this_ = static_cast<RespLogin&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.accesstoken_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RespLogin::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RespLogin(arena);
}
constexpr auto RespLogin::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RespLogin),
                                            alignof(RespLogin));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RespLogin::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RespLogin_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RespLogin::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RespLogin>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RespLogin::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RespLogin>(), &RespLogin::ByteSizeLong,
            &RespLogin::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RespLogin, _impl_._cached_size_),
        false,
    },
    &RespLogin::kDescriptorMethods,
    &descriptor_table_api_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RespLogin::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> RespLogin::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::RespLogin>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string accessToken = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RespLogin, _impl_.accesstoken_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string accessToken = 2;
    {PROTOBUF_FIELD_OFFSET(RespLogin, _impl_.accesstoken_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\13\0\0\0\0\0\0"
    "api.RespLogin"
    "accessToken"
  }},
};

PROTOBUF_NOINLINE void RespLogin::Clear() {
// @@protoc_insertion_point(message_clear_start:api.RespLogin)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.accesstoken_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RespLogin::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RespLogin& this_ = static_cast<const RespLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RespLogin::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RespLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:api.RespLogin)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string accessToken = 2;
          if (!this_._internal_accesstoken().empty()) {
            const std::string& _s = this_._internal_accesstoken();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "api.RespLogin.accessToken");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:api.RespLogin)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RespLogin::ByteSizeLong(const MessageLite& base) {
          const RespLogin& this_ = static_cast<const RespLogin&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RespLogin::ByteSizeLong() const {
          const RespLogin& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:api.RespLogin)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string accessToken = 2;
            if (!this_._internal_accesstoken().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_accesstoken());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RespLogin::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RespLogin*>(&to_msg);
  auto& from = static_cast<const RespLogin&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.RespLogin)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_accesstoken().empty()) {
    _this->_internal_set_accesstoken(from._internal_accesstoken());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RespLogin::CopyFrom(const RespLogin& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.RespLogin)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RespLogin::InternalSwap(RespLogin* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accesstoken_, &other->_impl_.accesstoken_, arena);
}

::google::protobuf::Metadata RespLogin::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RespPush::_Internal {
 public:
};

RespPush::RespPush(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:api.RespPush)
}
RespPush::RespPush(
    ::google::protobuf::Arena* arena,
    const RespPush& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RespPush* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:api.RespPush)
}

inline void* RespPush::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RespPush(arena);
}
constexpr auto RespPush::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(RespPush),
                                            alignof(RespPush));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RespPush::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RespPush_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RespPush::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<RespPush>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RespPush::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<RespPush>(), &RespPush::ByteSizeLong,
            &RespPush::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RespPush, _impl_._cached_size_),
        false,
    },
    &RespPush::kDescriptorMethods,
    &descriptor_table_api_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RespPush::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> RespPush::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::RespPush>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata RespPush::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_api_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
