// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto

#include "api.pb.h"
#include "api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace api {

static const char* AnalyticsServer_method_names[] = {
  "/api.AnalyticsServer/Hello",
  "/api.AnalyticsServer/Login",
  "/api.AnalyticsServer/PushMetrics",
  "/api.AnalyticsServer/GatewayUpsert",
  "/api.AnalyticsServer/GatewayDelete",
};

std::unique_ptr< AnalyticsServer::Stub> AnalyticsServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AnalyticsServer::Stub> stub(new AnalyticsServer::Stub(channel, options));
  return stub;
}

AnalyticsServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Hello_(AnalyticsServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(AnalyticsServer_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PushMetrics_(AnalyticsServer_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GatewayUpsert_(AnalyticsServer_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GatewayDelete_(AnalyticsServer_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AnalyticsServer::Stub::Hello(::grpc::ClientContext* context, const ::api::ReqHello& request, ::api::RespHello* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::ReqHello, ::api::RespHello, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Hello_, context, request, response);
}

void AnalyticsServer::Stub::async::Hello(::grpc::ClientContext* context, const ::api::ReqHello* request, ::api::RespHello* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::ReqHello, ::api::RespHello, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Hello_, context, request, response, std::move(f));
}

void AnalyticsServer::Stub::async::Hello(::grpc::ClientContext* context, const ::api::ReqHello* request, ::api::RespHello* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Hello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::RespHello>* AnalyticsServer::Stub::PrepareAsyncHelloRaw(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::RespHello, ::api::ReqHello, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Hello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::RespHello>* AnalyticsServer::Stub::AsyncHelloRaw(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AnalyticsServer::Stub::Login(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::api::RespLogin* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::ReqLogin, ::api::RespLogin, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void AnalyticsServer::Stub::async::Login(::grpc::ClientContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::ReqLogin, ::api::RespLogin, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void AnalyticsServer::Stub::async::Login(::grpc::ClientContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::RespLogin>* AnalyticsServer::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::RespLogin, ::api::ReqLogin, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::RespLogin>* AnalyticsServer::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AnalyticsServer::Stub::PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::api::RespPush* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::AnalyticsMetrics, ::api::RespPush, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushMetrics_, context, request, response);
}

void AnalyticsServer::Stub::async::PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::AnalyticsMetrics, ::api::RespPush, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMetrics_, context, request, response, std::move(f));
}

void AnalyticsServer::Stub::async::PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushMetrics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::RespPush>* AnalyticsServer::Stub::PrepareAsyncPushMetricsRaw(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::RespPush, ::api::AnalyticsMetrics, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushMetrics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::RespPush>* AnalyticsServer::Stub::AsyncPushMetricsRaw(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushMetricsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AnalyticsServer::Stub::GatewayUpsert(::grpc::ClientContext* context, const ::api::ReqGatewayUpsert& request, ::api::RespGatewaySync* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::ReqGatewayUpsert, ::api::RespGatewaySync, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GatewayUpsert_, context, request, response);
}

void AnalyticsServer::Stub::async::GatewayUpsert(::grpc::ClientContext* context, const ::api::ReqGatewayUpsert* request, ::api::RespGatewaySync* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::ReqGatewayUpsert, ::api::RespGatewaySync, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GatewayUpsert_, context, request, response, std::move(f));
}

void AnalyticsServer::Stub::async::GatewayUpsert(::grpc::ClientContext* context, const ::api::ReqGatewayUpsert* request, ::api::RespGatewaySync* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GatewayUpsert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::RespGatewaySync>* AnalyticsServer::Stub::PrepareAsyncGatewayUpsertRaw(::grpc::ClientContext* context, const ::api::ReqGatewayUpsert& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::RespGatewaySync, ::api::ReqGatewayUpsert, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GatewayUpsert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::RespGatewaySync>* AnalyticsServer::Stub::AsyncGatewayUpsertRaw(::grpc::ClientContext* context, const ::api::ReqGatewayUpsert& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGatewayUpsertRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AnalyticsServer::Stub::GatewayDelete(::grpc::ClientContext* context, const ::api::ReqGatewayDelete& request, ::api::RespGatewaySync* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::ReqGatewayDelete, ::api::RespGatewaySync, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GatewayDelete_, context, request, response);
}

void AnalyticsServer::Stub::async::GatewayDelete(::grpc::ClientContext* context, const ::api::ReqGatewayDelete* request, ::api::RespGatewaySync* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::ReqGatewayDelete, ::api::RespGatewaySync, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GatewayDelete_, context, request, response, std::move(f));
}

void AnalyticsServer::Stub::async::GatewayDelete(::grpc::ClientContext* context, const ::api::ReqGatewayDelete* request, ::api::RespGatewaySync* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GatewayDelete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::RespGatewaySync>* AnalyticsServer::Stub::PrepareAsyncGatewayDeleteRaw(::grpc::ClientContext* context, const ::api::ReqGatewayDelete& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::RespGatewaySync, ::api::ReqGatewayDelete, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GatewayDelete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::RespGatewaySync>* AnalyticsServer::Stub::AsyncGatewayDeleteRaw(::grpc::ClientContext* context, const ::api::ReqGatewayDelete& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGatewayDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

AnalyticsServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalyticsServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalyticsServer::Service, ::api::ReqHello, ::api::RespHello, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalyticsServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::ReqHello* req,
             ::api::RespHello* resp) {
               return service->Hello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalyticsServer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalyticsServer::Service, ::api::ReqLogin, ::api::RespLogin, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalyticsServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::ReqLogin* req,
             ::api::RespLogin* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalyticsServer_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalyticsServer::Service, ::api::AnalyticsMetrics, ::api::RespPush, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalyticsServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::AnalyticsMetrics* req,
             ::api::RespPush* resp) {
               return service->PushMetrics(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalyticsServer_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalyticsServer::Service, ::api::ReqGatewayUpsert, ::api::RespGatewaySync, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalyticsServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::ReqGatewayUpsert* req,
             ::api::RespGatewaySync* resp) {
               return service->GatewayUpsert(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalyticsServer_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalyticsServer::Service, ::api::ReqGatewayDelete, ::api::RespGatewaySync, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalyticsServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::ReqGatewayDelete* req,
             ::api::RespGatewaySync* resp) {
               return service->GatewayDelete(ctx, req, resp);
             }, this)));
}

AnalyticsServer::Service::~Service() {
}

::grpc::Status AnalyticsServer::Service::Hello(::grpc::ServerContext* context, const ::api::ReqHello* request, ::api::RespHello* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AnalyticsServer::Service::Login(::grpc::ServerContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AnalyticsServer::Service::PushMetrics(::grpc::ServerContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AnalyticsServer::Service::GatewayUpsert(::grpc::ServerContext* context, const ::api::ReqGatewayUpsert* request, ::api::RespGatewaySync* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AnalyticsServer::Service::GatewayDelete(::grpc::ServerContext* context, const ::api::ReqGatewayDelete* request, ::api::RespGatewaySync* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace api
#include <grpcpp/ports_undef.inc>

