// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto
#ifndef GRPC_api_2eproto__INCLUDED
#define GRPC_api_2eproto__INCLUDED

#include "api.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace api {

class AnalyticsServer final {
 public:
  static constexpr char const* service_full_name() {
    return "api.AnalyticsServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Logs in to the remote service
    virtual ::grpc::Status Hello(::grpc::ClientContext* context, const ::api::ReqHello& request, ::api::RespHello* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespHello>> AsyncHello(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespHello>>(AsyncHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespHello>> PrepareAsyncHello(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespHello>>(PrepareAsyncHelloRaw(context, request, cq));
    }
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::api::RespLogin* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespLogin>> AsyncLogin(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespLogin>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespLogin>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespLogin>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    // Pushes analytics data to the server
    virtual ::grpc::Status PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::api::RespPush* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespPush>> AsyncPushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespPush>>(AsyncPushMetricsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespPush>> PrepareAsyncPushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::api::RespPush>>(PrepareAsyncPushMetricsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Logs in to the remote service
      virtual void Hello(::grpc::ClientContext* context, const ::api::ReqHello* request, ::api::RespHello* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Hello(::grpc::ClientContext* context, const ::api::ReqHello* request, ::api::RespHello* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Login(::grpc::ClientContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Login(::grpc::ClientContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Pushes analytics data to the server
      virtual void PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::RespHello>* AsyncHelloRaw(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::RespHello>* PrepareAsyncHelloRaw(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::RespLogin>* AsyncLoginRaw(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::RespLogin>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::RespPush>* AsyncPushMetricsRaw(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::api::RespPush>* PrepareAsyncPushMetricsRaw(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Hello(::grpc::ClientContext* context, const ::api::ReqHello& request, ::api::RespHello* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespHello>> AsyncHello(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespHello>>(AsyncHelloRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespHello>> PrepareAsyncHello(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespHello>>(PrepareAsyncHelloRaw(context, request, cq));
    }
    ::grpc::Status Login(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::api::RespLogin* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespLogin>> AsyncLogin(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespLogin>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespLogin>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespLogin>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    ::grpc::Status PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::api::RespPush* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespPush>> AsyncPushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespPush>>(AsyncPushMetricsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespPush>> PrepareAsyncPushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::api::RespPush>>(PrepareAsyncPushMetricsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Hello(::grpc::ClientContext* context, const ::api::ReqHello* request, ::api::RespHello* response, std::function<void(::grpc::Status)>) override;
      void Hello(::grpc::ClientContext* context, const ::api::ReqHello* request, ::api::RespHello* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Login(::grpc::ClientContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response, std::function<void(::grpc::Status)>) override;
      void Login(::grpc::ClientContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response, std::function<void(::grpc::Status)>) override;
      void PushMetrics(::grpc::ClientContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::api::RespHello>* AsyncHelloRaw(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::api::RespHello>* PrepareAsyncHelloRaw(::grpc::ClientContext* context, const ::api::ReqHello& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::api::RespLogin>* AsyncLoginRaw(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::api::RespLogin>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::api::ReqLogin& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::api::RespPush>* AsyncPushMetricsRaw(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::api::RespPush>* PrepareAsyncPushMetricsRaw(::grpc::ClientContext* context, const ::api::AnalyticsMetrics& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Hello_;
    const ::grpc::internal::RpcMethod rpcmethod_Login_;
    const ::grpc::internal::RpcMethod rpcmethod_PushMetrics_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Logs in to the remote service
    virtual ::grpc::Status Hello(::grpc::ServerContext* context, const ::api::ReqHello* request, ::api::RespHello* response);
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response);
    // Pushes analytics data to the server
    virtual ::grpc::Status PushMetrics(::grpc::ServerContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Hello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* /*context*/, const ::api::ReqHello* /*request*/, ::api::RespHello* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHello(::grpc::ServerContext* context, ::api::ReqHello* request, ::grpc::ServerAsyncResponseWriter< ::api::RespHello>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Login() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::api::ReqLogin* /*request*/, ::api::RespLogin* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::api::ReqLogin* request, ::grpc::ServerAsyncResponseWriter< ::api::RespLogin>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PushMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PushMetrics() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_PushMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMetrics(::grpc::ServerContext* /*context*/, const ::api::AnalyticsMetrics* /*request*/, ::api::RespPush* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMetrics(::grpc::ServerContext* context, ::api::AnalyticsMetrics* request, ::grpc::ServerAsyncResponseWriter< ::api::RespPush>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Hello<WithAsyncMethod_Login<WithAsyncMethod_PushMetrics<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Hello() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::api::ReqHello, ::api::RespHello>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::api::ReqHello* request, ::api::RespHello* response) { return this->Hello(context, request, response); }));}
    void SetMessageAllocatorFor_Hello(
        ::grpc::MessageAllocator< ::api::ReqHello, ::api::RespHello>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::api::ReqHello, ::api::RespHello>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* /*context*/, const ::api::ReqHello* /*request*/, ::api::RespHello* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Hello(
      ::grpc::CallbackServerContext* /*context*/, const ::api::ReqHello* /*request*/, ::api::RespHello* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Login() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::api::ReqLogin, ::api::RespLogin>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::api::ReqLogin* request, ::api::RespLogin* response) { return this->Login(context, request, response); }));}
    void SetMessageAllocatorFor_Login(
        ::grpc::MessageAllocator< ::api::ReqLogin, ::api::RespLogin>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::api::ReqLogin, ::api::RespLogin>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::api::ReqLogin* /*request*/, ::api::RespLogin* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::api::ReqLogin* /*request*/, ::api::RespLogin* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PushMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PushMetrics() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::api::AnalyticsMetrics, ::api::RespPush>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::api::AnalyticsMetrics* request, ::api::RespPush* response) { return this->PushMetrics(context, request, response); }));}
    void SetMessageAllocatorFor_PushMetrics(
        ::grpc::MessageAllocator< ::api::AnalyticsMetrics, ::api::RespPush>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::api::AnalyticsMetrics, ::api::RespPush>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PushMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMetrics(::grpc::ServerContext* /*context*/, const ::api::AnalyticsMetrics* /*request*/, ::api::RespPush* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::api::AnalyticsMetrics* /*request*/, ::api::RespPush* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Hello<WithCallbackMethod_Login<WithCallbackMethod_PushMetrics<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Hello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* /*context*/, const ::api::ReqHello* /*request*/, ::api::RespHello* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Login() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::api::ReqLogin* /*request*/, ::api::RespLogin* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PushMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PushMetrics() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_PushMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMetrics(::grpc::ServerContext* /*context*/, const ::api::AnalyticsMetrics* /*request*/, ::api::RespPush* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Hello() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* /*context*/, const ::api::ReqHello* /*request*/, ::api::RespHello* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHello(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Login() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::api::ReqLogin* /*request*/, ::api::RespLogin* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PushMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PushMetrics() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_PushMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMetrics(::grpc::ServerContext* /*context*/, const ::api::AnalyticsMetrics* /*request*/, ::api::RespPush* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushMetrics(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Hello() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Hello(context, request, response); }));
    }
    ~WithRawCallbackMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* /*context*/, const ::api::ReqHello* /*request*/, ::api::RespHello* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Hello(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Login() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Login(context, request, response); }));
    }
    ~WithRawCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::api::ReqLogin* /*request*/, ::api::RespLogin* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PushMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PushMetrics() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PushMetrics(context, request, response); }));
    }
    ~WithRawCallbackMethod_PushMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushMetrics(::grpc::ServerContext* /*context*/, const ::api::AnalyticsMetrics* /*request*/, ::api::RespPush* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PushMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Hello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::api::ReqHello, ::api::RespHello>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::api::ReqHello, ::api::RespHello>* streamer) {
                       return this->StreamedHello(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Hello(::grpc::ServerContext* /*context*/, const ::api::ReqHello* /*request*/, ::api::RespHello* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::api::ReqHello,::api::RespHello>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Login() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::api::ReqLogin, ::api::RespLogin>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::api::ReqLogin, ::api::RespLogin>* streamer) {
                       return this->StreamedLogin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::api::ReqLogin* /*request*/, ::api::RespLogin* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::api::ReqLogin,::api::RespLogin>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PushMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PushMetrics() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::api::AnalyticsMetrics, ::api::RespPush>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::api::AnalyticsMetrics, ::api::RespPush>* streamer) {
                       return this->StreamedPushMetrics(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PushMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PushMetrics(::grpc::ServerContext* /*context*/, const ::api::AnalyticsMetrics* /*request*/, ::api::RespPush* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPushMetrics(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::api::AnalyticsMetrics,::api::RespPush>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Hello<WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_PushMetrics<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Hello<WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_PushMetrics<Service > > > StreamedService;
};

}  // namespace api


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_api_2eproto__INCLUDED
