// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api.proto
// Protobuf C++ Version: 5.29.3

#ifndef api_2eproto_2epb_2eh
#define api_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "analytics.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_api_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_api_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_api_2eproto;
namespace api {
class ReqHello;
struct ReqHelloDefaultTypeInternal;
extern ReqHelloDefaultTypeInternal _ReqHello_default_instance_;
class ReqLogin;
struct ReqLoginDefaultTypeInternal;
extern ReqLoginDefaultTypeInternal _ReqLogin_default_instance_;
class RespHello;
struct RespHelloDefaultTypeInternal;
extern RespHelloDefaultTypeInternal _RespHello_default_instance_;
class RespLogin;
struct RespLoginDefaultTypeInternal;
extern RespLoginDefaultTypeInternal _RespLogin_default_instance_;
class RespPush;
struct RespPushDefaultTypeInternal;
extern RespPushDefaultTypeInternal _RespPush_default_instance_;
}  // namespace api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace api {

// ===================================================================


// -------------------------------------------------------------------

class RespPush final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:api.RespPush) */ {
 public:
  inline RespPush() : RespPush(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RespPush* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RespPush));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RespPush(
      ::google::protobuf::internal::ConstantInitialized);

  inline RespPush(const RespPush& from) : RespPush(nullptr, from) {}
  inline RespPush(RespPush&& from) noexcept
      : RespPush(nullptr, std::move(from)) {}
  inline RespPush& operator=(const RespPush& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespPush& operator=(RespPush&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespPush& default_instance() {
    return *internal_default_instance();
  }
  static inline const RespPush* internal_default_instance() {
    return reinterpret_cast<const RespPush*>(
        &_RespPush_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(RespPush& a, RespPush& b) { a.Swap(&b); }
  inline void Swap(RespPush* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespPush* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespPush* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<RespPush>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const RespPush& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const RespPush& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "api.RespPush"; }

 protected:
  explicit RespPush(::google::protobuf::Arena* arena);
  RespPush(::google::protobuf::Arena* arena, const RespPush& from);
  RespPush(::google::protobuf::Arena* arena, RespPush&& from) noexcept
      : RespPush(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:api.RespPush)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RespPush& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_api_2eproto;
};
// -------------------------------------------------------------------

class RespLogin final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:api.RespLogin) */ {
 public:
  inline RespLogin() : RespLogin(nullptr) {}
  ~RespLogin() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RespLogin* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RespLogin));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RespLogin(
      ::google::protobuf::internal::ConstantInitialized);

  inline RespLogin(const RespLogin& from) : RespLogin(nullptr, from) {}
  inline RespLogin(RespLogin&& from) noexcept
      : RespLogin(nullptr, std::move(from)) {}
  inline RespLogin& operator=(const RespLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespLogin& operator=(RespLogin&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const RespLogin* internal_default_instance() {
    return reinterpret_cast<const RespLogin*>(
        &_RespLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(RespLogin& a, RespLogin& b) { a.Swap(&b); }
  inline void Swap(RespLogin* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespLogin* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespLogin* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RespLogin>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RespLogin& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RespLogin& from) { RespLogin::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RespLogin* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "api.RespLogin"; }

 protected:
  explicit RespLogin(::google::protobuf::Arena* arena);
  RespLogin(::google::protobuf::Arena* arena, const RespLogin& from);
  RespLogin(::google::protobuf::Arena* arena, RespLogin&& from) noexcept
      : RespLogin(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAccessTokenFieldNumber = 2,
  };
  // string accessToken = 2;
  void clear_accesstoken() ;
  const std::string& accesstoken() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_accesstoken(Arg_&& arg, Args_... args);
  std::string* mutable_accesstoken();
  PROTOBUF_NODISCARD std::string* release_accesstoken();
  void set_allocated_accesstoken(std::string* value);

  private:
  const std::string& _internal_accesstoken() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_accesstoken(
      const std::string& value);
  std::string* _internal_mutable_accesstoken();

  public:
  // @@protoc_insertion_point(class_scope:api.RespLogin)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      33, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RespLogin& from_msg);
    ::google::protobuf::internal::ArenaStringPtr accesstoken_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2eproto;
};
// -------------------------------------------------------------------

class RespHello final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:api.RespHello) */ {
 public:
  inline RespHello() : RespHello(nullptr) {}
  ~RespHello() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RespHello* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RespHello));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RespHello(
      ::google::protobuf::internal::ConstantInitialized);

  inline RespHello(const RespHello& from) : RespHello(nullptr, from) {}
  inline RespHello(RespHello&& from) noexcept
      : RespHello(nullptr, std::move(from)) {}
  inline RespHello& operator=(const RespHello& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespHello& operator=(RespHello&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespHello& default_instance() {
    return *internal_default_instance();
  }
  static inline const RespHello* internal_default_instance() {
    return reinterpret_cast<const RespHello*>(
        &_RespHello_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RespHello& a, RespHello& b) { a.Swap(&b); }
  inline void Swap(RespHello* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespHello* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespHello* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RespHello>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RespHello& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RespHello& from) { RespHello::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RespHello* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "api.RespHello"; }

 protected:
  explicit RespHello(::google::protobuf::Arena* arena);
  RespHello(::google::protobuf::Arena* arena, const RespHello& from);
  RespHello(::google::protobuf::Arena* arena, RespHello&& from) noexcept
      : RespHello(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChallengeFieldNumber = 2,
    kRevisionFieldNumber = 1,
  };
  // bytes challenge = 2;
  void clear_challenge() ;
  const std::string& challenge() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_challenge(Arg_&& arg, Args_... args);
  std::string* mutable_challenge();
  PROTOBUF_NODISCARD std::string* release_challenge();
  void set_allocated_challenge(std::string* value);

  private:
  const std::string& _internal_challenge() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_challenge(
      const std::string& value);
  std::string* _internal_mutable_challenge();

  public:
  // int32 revision = 1;
  void clear_revision() ;
  ::int32_t revision() const;
  void set_revision(::int32_t value);

  private:
  ::int32_t _internal_revision() const;
  void _internal_set_revision(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:api.RespHello)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RespHello& from_msg);
    ::google::protobuf::internal::ArenaStringPtr challenge_;
    ::int32_t revision_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2eproto;
};
// -------------------------------------------------------------------

class ReqLogin final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:api.ReqLogin) */ {
 public:
  inline ReqLogin() : ReqLogin(nullptr) {}
  ~ReqLogin() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReqLogin* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReqLogin));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReqLogin(
      ::google::protobuf::internal::ConstantInitialized);

  inline ReqLogin(const ReqLogin& from) : ReqLogin(nullptr, from) {}
  inline ReqLogin(ReqLogin&& from) noexcept
      : ReqLogin(nullptr, std::move(from)) {}
  inline ReqLogin& operator=(const ReqLogin& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqLogin& operator=(ReqLogin&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqLogin& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqLogin* internal_default_instance() {
    return reinterpret_cast<const ReqLogin*>(
        &_ReqLogin_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ReqLogin& a, ReqLogin& b) { a.Swap(&b); }
  inline void Swap(ReqLogin* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqLogin* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqLogin* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReqLogin>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReqLogin& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReqLogin& from) { ReqLogin::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReqLogin* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "api.ReqLogin"; }

 protected:
  explicit ReqLogin(::google::protobuf::Arena* arena);
  ReqLogin(::google::protobuf::Arena* arena, const ReqLogin& from);
  ReqLogin(::google::protobuf::Arena* arena, ReqLogin&& from) noexcept
      : ReqLogin(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kClientIdFieldNumber = 1,
    kHashFieldNumber = 2,
    kServerSideFieldNumber = 3,
  };
  // bytes clientId = 1;
  void clear_clientid() ;
  const std::string& clientid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_clientid(Arg_&& arg, Args_... args);
  std::string* mutable_clientid();
  PROTOBUF_NODISCARD std::string* release_clientid();
  void set_allocated_clientid(std::string* value);

  private:
  const std::string& _internal_clientid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(
      const std::string& value);
  std::string* _internal_mutable_clientid();

  public:
  // bytes hash = 2;
  void clear_hash() ;
  const std::string& hash() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_hash(Arg_&& arg, Args_... args);
  std::string* mutable_hash();
  PROTOBUF_NODISCARD std::string* release_hash();
  void set_allocated_hash(std::string* value);

  private:
  const std::string& _internal_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hash(
      const std::string& value);
  std::string* _internal_mutable_hash();

  public:
  // bool serverSide = 3;
  void clear_serverside() ;
  bool serverside() const;
  void set_serverside(bool value);

  private:
  bool _internal_serverside() const;
  void _internal_set_serverside(bool value);

  public:
  // @@protoc_insertion_point(class_scope:api.ReqLogin)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ReqLogin& from_msg);
    ::google::protobuf::internal::ArenaStringPtr clientid_;
    ::google::protobuf::internal::ArenaStringPtr hash_;
    bool serverside_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2eproto;
};
// -------------------------------------------------------------------

class ReqHello final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:api.ReqHello) */ {
 public:
  inline ReqHello() : ReqHello(nullptr) {}
  ~ReqHello() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReqHello* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReqHello));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReqHello(
      ::google::protobuf::internal::ConstantInitialized);

  inline ReqHello(const ReqHello& from) : ReqHello(nullptr, from) {}
  inline ReqHello(ReqHello&& from) noexcept
      : ReqHello(nullptr, std::move(from)) {}
  inline ReqHello& operator=(const ReqHello& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqHello& operator=(ReqHello&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReqHello& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReqHello* internal_default_instance() {
    return reinterpret_cast<const ReqHello*>(
        &_ReqHello_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ReqHello& a, ReqHello& b) { a.Swap(&b); }
  inline void Swap(ReqHello* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqHello* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReqHello* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReqHello>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReqHello& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReqHello& from) { ReqHello::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReqHello* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "api.ReqHello"; }

 protected:
  explicit ReqHello(::google::protobuf::Arena* arena);
  ReqHello(::google::protobuf::Arena* arena, const ReqHello& from);
  ReqHello(::google::protobuf::Arena* arena, ReqHello&& from) noexcept
      : ReqHello(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVersionFieldNumber = 1,
  };
  // int32 version = 1;
  void clear_version() ;
  ::int32_t version() const;
  void set_version(::int32_t value);

  private:
  ::int32_t _internal_version() const;
  void _internal_set_version(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:api.ReqHello)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ReqHello& from_msg);
    ::int32_t version_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ReqHello

// int32 version = 1;
inline void ReqHello::clear_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_ = 0;
}
inline ::int32_t ReqHello::version() const {
  // @@protoc_insertion_point(field_get:api.ReqHello.version)
  return _internal_version();
}
inline void ReqHello::set_version(::int32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:api.ReqHello.version)
}
inline ::int32_t ReqHello::_internal_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.version_;
}
inline void ReqHello::_internal_set_version(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_ = value;
}

// -------------------------------------------------------------------

// RespHello

// int32 revision = 1;
inline void RespHello::clear_revision() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.revision_ = 0;
}
inline ::int32_t RespHello::revision() const {
  // @@protoc_insertion_point(field_get:api.RespHello.revision)
  return _internal_revision();
}
inline void RespHello::set_revision(::int32_t value) {
  _internal_set_revision(value);
  // @@protoc_insertion_point(field_set:api.RespHello.revision)
}
inline ::int32_t RespHello::_internal_revision() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.revision_;
}
inline void RespHello::_internal_set_revision(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.revision_ = value;
}

// bytes challenge = 2;
inline void RespHello::clear_challenge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_.ClearToEmpty();
}
inline const std::string& RespHello::challenge() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:api.RespHello.challenge)
  return _internal_challenge();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RespHello::set_challenge(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:api.RespHello.challenge)
}
inline std::string* RespHello::mutable_challenge() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_challenge();
  // @@protoc_insertion_point(field_mutable:api.RespHello.challenge)
  return _s;
}
inline const std::string& RespHello::_internal_challenge() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.challenge_.Get();
}
inline void RespHello::_internal_set_challenge(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_.Set(value, GetArena());
}
inline std::string* RespHello::_internal_mutable_challenge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.challenge_.Mutable( GetArena());
}
inline std::string* RespHello::release_challenge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:api.RespHello.challenge)
  return _impl_.challenge_.Release();
}
inline void RespHello::set_allocated_challenge(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.challenge_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.challenge_.IsDefault()) {
    _impl_.challenge_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:api.RespHello.challenge)
}

// -------------------------------------------------------------------

// ReqLogin

// bytes clientId = 1;
inline void ReqLogin::clear_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.ClearToEmpty();
}
inline const std::string& ReqLogin::clientid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:api.ReqLogin.clientId)
  return _internal_clientid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ReqLogin::set_clientid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:api.ReqLogin.clientId)
}
inline std::string* ReqLogin::mutable_clientid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:api.ReqLogin.clientId)
  return _s;
}
inline const std::string& ReqLogin::_internal_clientid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientid_.Get();
}
inline void ReqLogin::_internal_set_clientid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.Set(value, GetArena());
}
inline std::string* ReqLogin::_internal_mutable_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.clientid_.Mutable( GetArena());
}
inline std::string* ReqLogin::release_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:api.ReqLogin.clientId)
  return _impl_.clientid_.Release();
}
inline void ReqLogin::set_allocated_clientid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.clientid_.IsDefault()) {
    _impl_.clientid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:api.ReqLogin.clientId)
}

// bytes hash = 2;
inline void ReqLogin::clear_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hash_.ClearToEmpty();
}
inline const std::string& ReqLogin::hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:api.ReqLogin.hash)
  return _internal_hash();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ReqLogin::set_hash(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hash_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:api.ReqLogin.hash)
}
inline std::string* ReqLogin::mutable_hash() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_hash();
  // @@protoc_insertion_point(field_mutable:api.ReqLogin.hash)
  return _s;
}
inline const std::string& ReqLogin::_internal_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hash_.Get();
}
inline void ReqLogin::_internal_set_hash(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hash_.Set(value, GetArena());
}
inline std::string* ReqLogin::_internal_mutable_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.hash_.Mutable( GetArena());
}
inline std::string* ReqLogin::release_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:api.ReqLogin.hash)
  return _impl_.hash_.Release();
}
inline void ReqLogin::set_allocated_hash(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hash_.IsDefault()) {
    _impl_.hash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:api.ReqLogin.hash)
}

// bool serverSide = 3;
inline void ReqLogin::clear_serverside() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serverside_ = false;
}
inline bool ReqLogin::serverside() const {
  // @@protoc_insertion_point(field_get:api.ReqLogin.serverSide)
  return _internal_serverside();
}
inline void ReqLogin::set_serverside(bool value) {
  _internal_set_serverside(value);
  // @@protoc_insertion_point(field_set:api.ReqLogin.serverSide)
}
inline bool ReqLogin::_internal_serverside() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.serverside_;
}
inline void ReqLogin::_internal_set_serverside(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.serverside_ = value;
}

// -------------------------------------------------------------------

// RespLogin

// string accessToken = 2;
inline void RespLogin::clear_accesstoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accesstoken_.ClearToEmpty();
}
inline const std::string& RespLogin::accesstoken() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:api.RespLogin.accessToken)
  return _internal_accesstoken();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RespLogin::set_accesstoken(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accesstoken_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:api.RespLogin.accessToken)
}
inline std::string* RespLogin::mutable_accesstoken() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_accesstoken();
  // @@protoc_insertion_point(field_mutable:api.RespLogin.accessToken)
  return _s;
}
inline const std::string& RespLogin::_internal_accesstoken() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.accesstoken_.Get();
}
inline void RespLogin::_internal_set_accesstoken(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accesstoken_.Set(value, GetArena());
}
inline std::string* RespLogin::_internal_mutable_accesstoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.accesstoken_.Mutable( GetArena());
}
inline std::string* RespLogin::release_accesstoken() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:api.RespLogin.accessToken)
  return _impl_.accesstoken_.Release();
}
inline void RespLogin::set_allocated_accesstoken(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accesstoken_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.accesstoken_.IsDefault()) {
    _impl_.accesstoken_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:api.RespLogin.accessToken)
}

// -------------------------------------------------------------------

// RespPush

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace api


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // api_2eproto_2epb_2eh
